##
## LeoFS Development Notes
##
## Note:
##   - Dependencies:
##       - united (pip install mkdocs-bootswatch)
##       - pygments (pip install pygments)
##       - pymdown-extensions (pip install pymdown-extensions)
##
site_name: LeoFS Development Notes
repo_url: https://github.com/leo-project/notes
repo_name: 'LeoFS Development Notes'
site_author: LeoProject
copyright: 'Copyright &copy; 2012-2018 LeoProject'
site_description: LeoFS Development Notes

docs_dir: 'docs'
theme:
    name: 'material'
    feature:
        tabs: true
markdown_extensions:
    - admonition
    - codehilite(linenums=true)
    - footnotes
    - meta
    - toc(permalink=true)
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
    - pymdownx.tasklist:
        custom_checkbox: true
    - toc:
        permalink: True
        separator: "_"

pages:
- Introduction: 'index.md'
- Benchmark:
    - v1.3.0:
        - Performance Tests with/without Object Cache:
            - With Cache Benchmark#1: 'benchmark/leofs/1.3/1.3.0/front/20160808_15m_f10k_r95w5_dc_mc_30min_1/README.md'
            - With Cache Benchmark#2: 'benchmark/leofs/1.3/1.3.0/front/20160808_15m_f10k_r95w5_mc_30min_1/README.md'
            - Without Cache Benchmark#1: 'benchmark/leofs/1.3/1.3.0/front/20160808_15m_f10k_r95w5_nocache_30min_1/README.md'
            - Without Cache Benchmark#2: 'benchmark/leofs/1.3/1.3.0/front/20160912_image_f10m_r100_nocache_30min_1/README.md'
        - Performance Tests:
            - Performance Test#1: 'benchmark/leofs/1.3/1.3.0/front/20160912_image_f20m_r100_n15_300min_1/README.md'
            - Performance Test#2: 'benchmark/leofs/1.3/1.3.0/front/20160912_image_f50m_r100_n15_30min_1/README.md'
            - Performance Test - Large Object#1: 'benchmark/leofs/1.3/1.3.0/front/20160919_large1g_f500_rw_1/README.md'
            - Performance Test - Large Object#2: 'benchmark/leofs/1.3/1.3.0/front/20161005_large1g_f500_rw_1/README.md'
            - Performance Test - Photo Size#1: 'benchmark/leofs/1.3/1.3.0/front/20161006_image_f20m_rw_1/README.md'
            - Performance Test - Photo Size#2: 'benchmark/leofs/1.3/1.3.0/front/20161007_image_f4m_rw_nodekill_1/README.md'
            - Performance Test - Fixed Size#1: 'benchmark/leofs/1.3/1.3.0/front/20161011_fix50m_f4k_read_seq_1/README.md'
            - Performance Test - Fixed Size#2: 'benchmark/leofs/1.3/1.3.0/front/20161011_fix50m_f4k_read_seq_2/README.md'
            - Performance Test - Large Object#3: 'benchmark/leofs/1.3/1.3.0/front/20161013_large1g_f500_rw_1/README.md'
    - v1.3.1:
        - Comparison Between Erlang/OTP's Versions:
            - Performance Test w/Erlang/OTP 17#1: 'benchmark/leofs/1.3/1.3.1/front/20161014_image_f4m_rw_otp17_1/README.md'
            - Performance Test w/Erlang/OTP 17#2: 'benchmark/leofs/1.3/1.3.1/front/20161017_15m_f40k_rw_otp17_1/README.md'
            - Performance Test w/Erlang/OTP 17#3: 'benchmark/leofs/1.3/1.3.1/front/20161017_leofs1m_f1m_rw_otp17_1/README.md'
            - Performance Test w/Erlang/OTP 17#4: 'benchmark/leofs/1.3/1.3.1/front/20161018_s3cmd1g_f500_rw_otp17_1/README.md'
            - Performance Test w/Erlang/OTP 18#1: 'benchmark/leofs/1.3/1.3.1/front/20161013_image_f4m_rw_otp18_1/README.md'
            - Performance Test w/Erlang/OTP 18#2: 'benchmark/leofs/1.3/1.3.1/front/20161017_15m_f40k_rw_otp18_1/README.md'
            - Performance Test w/Erlang/OTP 18#3: 'benchmark/leofs/1.3/1.3.1/front/20161017_leofs1m_f1m_rw_otp18_1/README.md'
            - Performance Test w/Erlang/OTP 18#4: 'benchmark/leofs/1.3/1.3.1/front/20161018_s3cmd1g_f500_rw_otp18_1/README.md'
            - Performance Test w/Erlang/OTP 19#1: 'benchmark/leofs/1.3/1.3.1/front/20161013_image_f4m_rw_otp19_1/README.md'
            - Performance Test w/Erlang/OTP 19#2: 'benchmark/leofs/1.3/1.3.1/front/20161017_15m_f40k_rw_otp19_1/README.md'
            - Performance Test w/Erlang/OTP 19#3: 'benchmark/leofs/1.3/1.3.1/front/20161017_leofs1m_f1m_rw_otp19_1/README.md'
            - Performance Test w/Erlang/OTP 19#4: 'benchmark/leofs/1.3/1.3.1/front/20161018_s3cmd1g_f500_rw_otp19_1/README.md'
        - Ramge-Get Tests:
            - Range-Get Test#1 : 'benchmark/leofs/1.3/1.3.1/front/20161116_fix1m_f300k_range_100k_1/README.md'
            - Range-Get Test#2 : 'benchmark/leofs/1.3/1.3.1/front/20161116_fix50m_f6k_range_1m_1/README.md'
            - Range-Get Test#3 : 'benchmark/leofs/1.3/1.3.1/front/20161117_fix50m_f6k_range_100k_1/README.md'
            - Range-Get Test#4 : 'benchmark/leofs/1.3/1.3.1/front/20161117_fix50m_f6k_range_200k_1/README.md'
            - Range-Get Test#5 : 'benchmark/leofs/1.3/1.3.1/front/20161122_fix1m_f300k_range_200k_1/README.md'
            - Range-Get Test#6 : 'benchmark/leofs/1.3/1.3.1/front/20161122_fix200m_f1.5m_read_1/README.md'
        - NFS Tests:
            - Performance Test#1 : 'benchmark/leofs/1.3/1.3.1/nfs/20161121_fix1m_f10k_rw_1/README.md'
            - Performance Test#2 : 'benchmark/leofs/1.3/1.3.1/nfs/20161122_128k_dir20_f500_rw_5min_1/README.md'
        - Other Tests:
            - Comparison with/without Disk Watchdog: 'benchmark/leofs/1.3/1.3.1/front/20161018_image_f10m_load_watchdog_1/README.md'
            - Performance Test w/leveldb: 'benchmark/leofs/1.3/1.3.1/front/20161216_image_f4m_load_eleveldb_1/README.md'
            - Performance Test#1: 'benchmark/leofs/1.3/1.3.1/front/20161228_image_f4m_load_r95w5_node4_ssd_30min_1/README.md'
            - Performance Test#2: 'benchmark/leofs/1.3/1.3.1/front/20161228_image_f4m_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#3: 'benchmark/leofs/1.3/1.3.1/front/20161228_leofs1m_f1m_load_read_r95w5_ssd_30min_1/README.md'
            - Overload Test: 'benchmark/leofs/1.3/1.3.1/overload/20161024_image_f4m_load_rate200_overload_1/README.md'
            - Rolling Upgrade Test#1: 'benchmark/leofs/1.3/1.3.1/upgrade/20161020_1.2.18_rolling_rw_1/README.md'
            - Rolling Upgrade Test#2: 'benchmark/leofs/1.3/1.3.1/upgrade/20161020_1.3.0_rolling_rw_1/README.md'
    - v1.3.2:
        - Performance Tests:
            - Performance Test#1: 'benchmark/leofs/1.3/1.3.2/front/20170111_image_f4m_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#2: 'benchmark/leofs/1.3/1.3.2/front/20170111_leofs1m_f1m_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#3: 'benchmark/leofs/1.3/1.3.2/front/20170112_leofs5m_f40k_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#4: 'benchmark/leofs/1.3/1.3.2/front/20170118_image_f4m_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#5: 'benchmark/leofs/1.3/1.3.2/front/20170118_leofs1m_f1m_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#6: 'benchmark/leofs/1.3/1.3.2/front/20170119_s3cmd1g_f500_load_read_w96buf0_30min_1/README.md'
            - Performance Test#7: 'benchmark/leofs/1.3/1.3.2/front/20170120_leofs15m_f40k_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#8: 'benchmark/leofs/1.3/1.3.2/front/20170120_s3cmd1g_f500_load_read_30min_1/README.md'
            - Performance Test#9: 'benchmark/leofs/1.3/1.3.2/front/20170130_image_f4m_read_ssd_10min_read_quo_1/README.md'
            - Performance Test#10: 'benchmark/leofs/1.3/1.3.2/front/20170328_image_f4m_load_read_r95w5_ssd3710_30min_1/README.md'
            - Performance Test#11: 'benchmark/leofs/1.3/1.3.2/front/20170525_image_f4m_load_read_nvme_30min_1/README.md'
            - Performance Test#12: 'benchmark/leofs/1.3/1.3.2/front/20171109_fix10m_f20k_load_read_r95w5_ssd_30min_1/README.md'
    - v1.3.3:
        - Performance Tests:
            - Performance Test#1: 'benchmark/leofs/1.3/1.3.3/front/20170331_image_f4m_load_read_manager_30min_1/README.md'
            - Performance Test#2: 'benchmark/leofs/1.3/1.3.3/front/20170420_image_f4m_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#3: 'benchmark/leofs/1.3/1.3.3/front/20170421_leofs15m_f40k_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#4: 'benchmark/leofs/1.3/1.3.3/front/20170421_leofs1m_f1m_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#5: 'benchmark/leofs/1.3/1.3.3/front/20170421_s3cmd1g_f500_load_read_30min_1/README.md'
    - v1.3.5:
        - Performance Tests:
            - Performance Test#1: 'benchmark/leofs/1.3/1.3.5/front/20170808_image_f4m_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#2: 'benchmark/leofs/1.3/1.3.5/front/20170809_leofs15m_f40k_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#3: 'benchmark/leofs/1.3/1.3.5/front/20170809_s3cmd1g_f500_load_read_30min_1/README.md'
    - v1.3.7:
        - Performance Tests:
            - Performance Test#1: 'benchmark/leofs/1.3/1.3.7/front/20170911_image_f4m_load_read_r95w5_r80w20_ssd_30min_1/README.md'
            - Performance Test#2: 'benchmark/leofs/1.3/1.3.7/front/20170912_image_f4m_load_read_r95w5_ssd_30min_1/README.md'
    - v1.3.8:
        - Performance Tests:
            - Performance Test#1: 'benchmark/leofs/1.3/1.3.8/front/20171013_image_f4m_load_read_lager_leologger_ssd_30min_1/README.md'
            - Performance Test#2: 'benchmark/leofs/1.3/1.3.8/front/20171108_fix10m_f20k_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#3: 'benchmark/leofs/1.3/1.3.8/front/20171115_image_f4m_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#4: 'benchmark/leofs/1.3/1.3.8/front/20171120_image_f4m_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#5: 'benchmark/leofs/1.3/1.3.8/front/20171120_leofs15m_f40k_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#6: 'benchmark/leofs/1.3/1.3.8/front/20171120_leofs1m_f1m_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#7: 'benchmark/leofs/1.3/1.3.8/front/20171120_s3cmd10m_f20k_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#8: 'benchmark/leofs/1.3/1.3.8/front/20171120_s3cmd1g_f500_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#9: 'benchmark/leofs/1.3/1.3.8/front/20171121_image_f4m_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#10: 'benchmark/leofs/1.3/1.3.8/front/20171121_leofs15m_f40k_load_read_r95w5_ssd_30min_1/README.md'
            - Performance Test#11: 'benchmark/leofs/1.3/1.3.8/front/20171121_leofs1m_f1m_load_read_r95w5_ssd_30min_1/README.md'
